######################################################################
#You get more help at http://dev.bukkit.org/server-mods/simple-info2 #
#You can use %sender% to get the name of the command-sender!         #
#You can use %realtime% to get the machine-time of the server!       #
#You can use %onlineplayers% to get how many players are online      #
#You can use %world% to get the senders world                        #
######################################################################


#Do not change
Version: ${config.version}

SearchForUpdates: true

NoPermissionMessage: '&cSorry, %player%, you dont have permission to do this.'
CommandIsBlocked: '&cSorry, %player%, the command %cmd% is blocked in %world%.'

Commands:
  
  /tptest:
    mode: 'teleport'
    permission: 'myoc.tpest'
    sendTo: 'sender'
    messages: 
    - '&cTeleporting to coords...'
    - '&ePlease wait for the timer...'
    delay: 3.0
    permission: 'myoc.tptest'
    world: 'world'
    x: 100.0
    y: 100.0
    z: 100.0
    pitch: 0.0
    yaw: 0.0
    
  /msgtest:
    mode: 'message'
    permission: 'myoc.msgtest'
    sendTo: 'sender'
    messages: 
    - '&aThis is only a test!'
    
  /alias:
    mode: 'alias'
    permission: 'myoc.alias'
    sendTo: 'sender'
    messages: 
    - '&cExecuting /say I am a test'
    execute: '/say I am a test!'
    
BlockedWorlds:
    world:
    - '/alias'
    - '/msgtest'
    
    
  