######################################################################
#You get more help at http://dev.bukkit.org/server-mods/simple-info2 #
#You can use %sender% to get the name of the command-sender!         #
#You can use %realtime% to get the machine-time of the server!       #
#You can use %onlineplayers% to get how many players are online      #
#You can use %world% to get the senders world                        #
######################################################################


NoPermissionMessage: '&cSorry, %player%, you dont have permission to do this.'
CommandIsBlocked: '&cSorry, %player%, the command %cmd% is blocked in %world%.'

Commands:
  
  /tptest:
    mode: 'teleport'
    permission: 'myoc.tpest'
    sendTo: 'sender'
    messages: 
    - '&cTeleporting to coords...'
    - '&ePlease wait for the timer...'
    #use 0 for no delay
    delay: 3
    permission: 'myoc.tptest'
    world: 'world'
    x: 100.0
    y: 100.0
    z: 100.0
    pitch: 0.0
    yaw: 0.0
    
  /msgtest:
    mode: 'message'
    permission: 'myoc.msgtest'
    sendTo: 'sender'
    messages: 
    - '&aThis is only a test!'
    
  /alias:
    mode: 'alias'
    permission: 'myoc.alias'
    sendTo: 'sender'
    messages: 
    - '&cExecuting multiple commands...'
    execute: 
    - 'say I am a test!'
    - 'say I am a test 2!'
    
  /items:
    mode: 'item'
    permission: 'myoc.item'
    sendTo: 'sender'
    messages:
    - 'item'
    Item:
      Material: DIRT
      Amount: 7
    
BlockedWorlds:
    testworld:
    - '/alias'
    - '/msgtest'
    
    
  