name: ${project.artifactId}
version: ${project.version}
description: Make your own commands without learn how to programm
author: TheJeterLP
website: http://dev.bukkit.org/server-mods/simple-info2
main: de.JeterLP.MakeYourOwnCommands.Main

commands:
  myoc:
    usage: /<command> <reload|list>
    description: Main command
    aliases: [sinfo]
